language: bash

services:
  - docker

env:
  global:
    - IMAGE_VERSION=v1
    - DOCKER_REPO=jman777

before_install:
  - echo "Starting CI pipeline..."

script:
  # Build Docker images
  - docker-compose -f docker-compose-build.yaml build --parallel
    #- docker build -t udagram-api-feed ./udagram-api-feed
    #- docker build -t udagram-api-user ./udagram-api-user
    #- docker build -t udagram-frontend ./udagram-frontend
    #- docker build -t udagram-reverseproxy ./udagram-reverseproxy

  # Tag Docker images
  - docker tag udagram-api-feed $DOCKER_REPO/udagram-api-feed:$IMAGE_VERSION
  - docker tag udagram-api-user $DOCKER_REPO/udagram-api-user:$IMAGE_VERSION
  - docker tag udagram-frontend $DOCKER_REPO/udagram-frontend:$IMAGE_VERSION
  - docker tag udagram-reverseproxy $DOCKER_REPO/udagram-reverseproxy:$IMAGE_VERSION

  # Push Docker images to DockerHub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push $DOCKER_REPO/udagram-api-feed:$IMAGE_VERSION
  - docker push $DOCKER_REPO/udagram-api-user:$IMAGE_VERSION
  - docker push $DOCKER_REPO/udagram-frontend:$IMAGE_VERSION
  - docker push $DOCKER_REPO/udagram-reverseproxy:$IMAGE_VERSION

notifications:
  email:
    recipients:
      - $EMAIL
    on_success: always
    on_failure: always
